using FiftyOneDegrees.Business.Attributes;

namespace FiftyOneDegrees.Enums
{
    public enum FeatureSupport
    {
        [FiftyOneKey("Canvas")]
        BrowserCanvas,
        [FiftyOneKey("CssBackground")]
        CssBackground,
        [FiftyOneKey("CssBorderImage")]
        CssBorderImage,
        [FiftyOneKey("CssCanvas")]
        CssCanvas,
        [FiftyOneKey("CssColor")]
        CssColor,
        [FiftyOneKey("CssColumn")]
        CssColumn,
        [FiftyOneKey("CssFlexbox")]
        CssFlexBox,
        [FiftyOneKey("CssFont")]
        CssFont,
        [FiftyOneKey("CssImages")]
        CssImages,
        [FiftyOneKey("CssMediaQueries")]
        CssMediaQueries,
        [FiftyOneKey("CssMinMax")]
        CssMinMax,
        [FiftyOneKey("CssOverflow")]
        CssOverflow,
        [FiftyOneKey("CssPosition")]
        CssPosition,
        [FiftyOneKey("CssText")]
        CssText,
        [FiftyOneKey("CssTransforms")]
        CssTransforms,
        [FiftyOneKey("CssTransitions")]
        CssTransitions,
        [FiftyOneKey("CssUI")]
        CssUI,
        [FiftyOneKey("DataSet")]
        DataAttributes,
        [FiftyOneKey("DataUrl")]
        DataEncodedUrl,
        [FiftyOneKey("DeviceOrientation")]
        DeviceOrientation,
        [FiftyOneKey("FileReader")]
        FileReader,
        [FiftyOneKey("FileSaver")]
        FileSaver,
        [FiftyOneKey("FileWriter")]
        FileWriter,
        [FiftyOneKey("AnimationTiming")]
        AnimationTiming,
        [FiftyOneKey("BlobBuilder")]
        BlobBuilder,
        [FiftyOneKey("FormData")]
        FormData,
        [FiftyOneKey("Iframe")]
        IFrame,
        [FiftyOneKey("IndexedDB")]
        LocalDatabase,
        [FiftyOneKey("Masking")]
        Masking,
        [FiftyOneKey("PostMessage")]
        PostMessage,
        [FiftyOneKey("Prompts")]
        Prompts,
        [FiftyOneKey("Selector")]
        Selector,
        [FiftyOneKey("TouchEvents")]
        TouchEvents,
        [FiftyOneKey("TextTracking")]
        TextTracking,
        [FiftyOneKey("GeoLocation")]
        Geolocation,
        [FiftyOneKey("Html5")]
        HTML5,
        [FiftyOneKey("Html-Media-Capture")]
        HTMLMediaCapture,
        [FiftyOneKey("Json")]
        Json,
        [FiftyOneKey("Fullscreen")]
        FullScreen,
        [FiftyOneKey("SupportsWebGL")]
        WebGL,
        [FiftyOneKey("Svg")]
        SVG,
        [FiftyOneKey("Video")]
        Video,
        [FiftyOneKey("Viewport")]
        Viewport,
        [FiftyOneKey("History")]
        History,
        [FiftyOneKey("Meter")]
        Meter,
        [FiftyOneKey("Progress")]
        Progress,
        [FiftyOneKey("WebWorkers")]
        WebWorkers,
        [FiftyOneKey("Xhr2")]
        XHR2Ajax
    }
}
